env:
  global:
  - CC_TEST_REPORTER_ID=833e64d9449ba30a078ad95c5fecbae28b7f09b2217b548811a5e2c5d2a1e93b
language: node_js
node_js:
  - lts/*
cache: yarn

install:
  - yarn install

before_script:
  - yarn global add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - nyc --reporter=lcov yarn run unit
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT